In [ ]:
import pandas as pd

train = pd.read_csv("train_aWnotuB.csv")
train.head()

In [ ]:
print(train.shape)
print(train.columns)
train.info()

In [ ]:
train.head(10)

In [ ]:
train['Year'] = train['DateTime'].dt.year
train['Month'] = train['DateTime'].dt.month
train['Day'] = train['DateTime'].dt.day
train['Hour'] = train['DateTime'].dt.hour

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.plot(train['Vehicles'][:1000])
plt.title("Traffic Flow")
plt.show()

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X = train[['Year','Month','Day','Hour','Junction']]
y = train['Vehicles']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor()
model.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, pred)

print("MAE:", mae)

In [ ]:
import joblib

joblib.dump(model, "traffic_model.pkl")

In [ ]:
train.isnull().sum()

In [ ]:
import matplotlib.pyplot as plt

train.groupby('Junction')['Vehicles'].mean().plot(kind='bar')

plt.title("Average Traffic by Junction")
plt.show()

In [ ]:
train.groupby('Hour')['Vehicles'].mean().plot()

plt.title("Traffic by Hour")
plt.show()

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train,y_train)

pred_lr = lr.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error

mae_lr = mean_absolute_error(y_test,pred_lr)

print(mae_lr)

In [ ]:
mae_rf = mean_absolute_error(y_test,pred)

print("Random Forest:",mae_rf)
print("Linear Regression:",mae_lr)

In [ ]:
plt.figure(figsize=(10,5))

plt.plot(y_test.values[:100],label="Actual")

plt.plot(pred[:100],label="Predicted")

plt.legend()

plt.show()

In [ ]:
results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": pred
})

results.head()

In [ ]:
results.to_csv("traffic_predictions.csv",index=False)

In [ ]:
!ls

In [ ]:
from google.colab import files
files.download("traffic_predictions.csv")

In [ ]:
import joblib
joblib.dump(model, "traffic_model.pkl")

In [ ]:
from google.colab import files
files.download("traffic_model.pkl")

In [ ]:
results = pd.DataFrame({
    'Actual': y_test,
    'Predicted': pred
})

results.head()

In [ ]:
results.to_csv("traffic_predictions.csv", index=False)

In [ ]:
from google.colab import files

files.download("traffic_predictions.csv")

In [ ]:
%whos

In [ ]:
import os

print(os.listdir())

['.config', '.ipynb_checkpoints', 'datasets_8494_11879_test_BdBKkAj.csv', 'train_aWnotuB.csv', 'sample_data']

In [ ]:
import os

print(os.listdir())

['.config', '.ipynb_checkpoints', 'datasets_8494_11879_test_BdBKkAj.csv', 'train_aWnotuB.csv', 'sample_data']

In [ ]:
import pandas as pd

train = pd.read_csv("train_aWnotuB.csv")
test = pd.read_csv("datasets_8494_11879_test_BdBKkAj.csv")

print(train.shape)
print(test.shape)

(48120, 4)
(11808, 3)

In [ ]:
train['DateTime'] = pd.to_datetime(train['DateTime'])

train['Year'] = train['DateTime'].dt.year
train['Month'] = train['DateTime'].dt.month
train['Day'] = train['DateTime'].dt.day
train['Hour'] = train['DateTime'].dt.hour

train.head()

             DateTime  Junction  Vehicles           ID  Year  Month  Day  Hour
0 2015-11-01 00:00:00         1        15  20151101001  2015     11    1     0
1 2015-11-01 01:00:00         1        13  20151101011  2015     11    1     1
2 2015-11-01 02:00:00         1        10  20151101021  2015     11    1     2
3 2015-11-01 03:00:00         1         7  20151101031  2015     11    1     3
4 2015-11-01 04:00:00         1         9  20151101041  2015     11    1     4

In [ ]:
X = train[['Junction','Year','Month','Day','Hour']]

y = train['Vehicles']

print(X.head())
print(y.head())

   Junction  Year  Month  Day  Hour
0         1  2015     11    1     0
1         1  2015     11    1     1
2         1  2015     11    1     2
3         1  2015     11    1     3
4         1  2015     11    1     4
0    15
1    13
2    10
3     7
4     9
Name: Vehicles, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(38496, 5)
(9624, 5)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model Training Completed")

Model Training Completed

In [ ]:
pred = model.predict(X_test)

print(pred[:10])

[ 9.18 57.22  8.4  10.56 18.47 10.12 12.81 14.8  12.8  20.79]

In [ ]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, pred)

print("MAE:", mae)

MAE: 2.8641843308395676

In [ ]:
results = pd.DataFrame({
    'Actual': y_test,
    'Predicted': pred
})

results.head()

       Actual  Predicted
24632       9       9.18
36428      97      57.22
42150      13       8.40
23885      11      10.56
2174       24      18.47

In [ ]:
results.to_csv("traffic_predictions.csv", index=False)

print("CSV Saved")

CSV Saved

In [ ]:
import joblib

joblib.dump(model, "traffic_model.pkl")

print("Model Saved")

Model Saved

In [ ]:
import os

print(os.listdir())

['.config', 'traffic_model.pkl', '.ipynb_checkpoints', 'traffic_predictions.csv', 'datasets_8494_11879_test_BdBKkAj.csv', 'train_aWnotuB.csv', 'sample_data']

In [ ]:
from google.colab import files

files.download("traffic_predictions.csv")
files.download("traffic_model.pkl")

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=20,
    random_state=42
)

In [ ]:
n_estimators=100

In [ ]:
import joblib
joblib.dump(model, "traffic_model.pkl")

['traffic_model.pkl']

In [ ]:
from sklearn.ensemble import RandomForestRegressor

small_model = RandomForestRegressor(
    n_estimators=20,
    random_state=42
)

small_model.fit(X_train, y_train)

print("Small Model Training Completed")

Small Model Training Completed

In [ ]:
import joblib

joblib.dump(small_model, "traffic_model_small.pkl")

print("Model Saved")

Model Saved

In [ ]:
import os

size = os.path.getsize("traffic_model_small.pkl")

print("Size in MB:", size/(1024*1024))

Size in MB: 60.790589332580566

In [3]:
%whos

Variable   Type      Data/Info
------------------------------
joblib     module    <module 'joblib' from '/u<...>ages/joblib/__init__.py'>
os         module    <module 'os' (frozen)>

In [4]:
import pandas as pd

train = pd.read_csv("train_aWnotuB.csv")

In [7]:
train['DateTime'] = pd.to_datetime(train['DateTime'])

train['Year'] = train['DateTime'].dt.year
train['Month'] = train['DateTime'].dt.month
train['Day'] = train['DateTime'].dt.day
train['Hour'] = train['DateTime'].dt.hour

In [8]:
X = train[['Junction','Year','Month','Day','Hour']]
y = train['Vehicles']

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=50,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=50, random_state=42)

In [11]:
import joblib

joblib.dump(model, "traffic_model_new.pkl")

['traffic_model_new.pkl']

In [12]:
import os

print(
    os.path.getsize("traffic_model_new.pkl") /
    (1024*1024),
    "MB"
)

151.900071144104 MB

In [13]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=10,
    max_depth=8,
    random_state=42
)

model.fit(X_train,y_train)

joblib.dump(model,"traffic_model_small.pkl")

['traffic_model_small.pkl']

In [14]:
import os

print(
    os.path.getsize("traffic_model_small.pkl") /
    (1024*1024),
    "MB"
)

0.3523721694946289 MB

In [15]:
from google.colab import files

files.download("traffic_model_small.pkl")

In [16]:
pred = model.predict(X_test)

In [17]:
import pandas as pd

results = pd.DataFrame({
    'Actual': y_test,
    'Predicted': pred
})

In [18]:
results.to_csv("traffic_predictions.csv", index=False)

print("Saved Successfully")

Saved Successfully

In [19]:
from google.colab import files

files.download("traffic_predictions.csv")